
Criando uma Tabela Calendário no Power BI

Descobrir as datas iniciais e finais existentes na tabela base (Onde as análises por data serão realizadas)
* Alterar os nomes das etapas manualmente: Página Inicial -> Editor Avançado

Criando a Função (Eatapa por Etapa)

Página Inicial -> Nova Fonte -> Consulta Nula

= List.Min(BaseVendas[Data da Venda])  (Renomear para: DataMin)

-> Próxima Etapa -> Botão Direito em cima de Etapa -> Inserir Próxima Etapa

= List.Max(BaseVendas[Data da Venda])  (Renomear para: DataMax)

-> Próxima Etapa -> Botão Direito em cima de Etapa -> Inserir Próxima Etapa

= Duration.Days(DataMax - DataMin) + 1  (Renomear para: QtdeDias)

-> Próxima Etapa -> Botão Direito em cima de Etapa -> Inserir Próxima Etapa

= List.Dates(DataMin, QtdeDias, #duration(1, 0, 0, 0)) (Renomear para: ListaDatas)

-> Clicar na lista gerada -> Guia Transformar -> Para a Tabela -> Ok
-> Alterar o nome da coluna da nova tabela, e alterar seu tipo para Data
-> Alterar o nome da Tabela para: Calendario

Incluir os Tipos de Análises:

-> Clicar na coluna Data
-> Menu: Adicionar Coluna -> Data 
-> Ano -> Ano

Repetir para os tipos:

-> Mês -> Mês
-> Mês -> Nome do Mês
-> Mês -> Ínicio do Mês

-> Trimestre -> Trimestre
-> Semana -> Semana do Ano

Função Pronta:
-> ATENÇÃO: Ao copiar/colar a função abaixo, atente-se as Tabelas utilizadas as quais provavelmente
possuirão os nomes diferentes das tulizadas por você para análise por datas. Estas tabelas são referidas
na criação das variáveis: DataMin e DataMx.

let
    DataMin = List.Min(BaseVendas[Data da Venda]),
    DataMax = List.Max(BaseVendas[Data da Venda]),
    QtdeDias = Duration.Days(DataMax - DataMin) + 1,
    ListaDatas = List.Dates(DataMin, QtdeDias, #duration(1, 0, 0, 0)),
    #"Convertido para Tabela" = Table.FromList(ListaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Datas"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Datas", type date}}),
    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Datas]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Datas]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Datas]), type text),
    #"Início do Mês Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Início do Mês", each Date.StartOfMonth([Datas]), type date),
    #"Trimestre Inserido" = Table.AddColumn(#"Início do Mês Inserido", "Trimestre", each Date.QuarterOfYear([Datas]), Int64.Type),
    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Datas]), Int64.Type)
in
    #"Semana do Ano Inserida"
